### ISSUE TITLE
"Grünen" wird nicht zensiert

### ISSUE THREAD

**Issue by gruselhaus** [Parteiduell/frontend#14]
<img width="1792" alt="Bildschirmfoto 2019-11-14 um 23 46 15" src="https://user-images.githubusercontent.com/33380107/68902586-095f6b00-0739-11ea-9ae7-5011fb82ab3d.png">

**Comment by jnnkB** [comment]
Hast du die URL zum überprüfen?

**Comment by gruselhaus** [comment]
@jnnkB https://parteiduell.de/#WOM-6-3:CDU/CSU,DIE%20LINKE,GRÜNE,SPD:A
