### ISSUE TITLE
Weird Bug

### ISSUE THREAD

**Issue by gruselhaus** [Parteiduell/frontend#53]
@jnnkB kannst Du dir das bitte mal anschauen?

https://youtu.be/Wx5tpS-eyyw

**Comment by jnnkB** [comment]
Den Fehler hatten wir jetzt schon nen paar mal. Das letzte mal eingführt haben wir Ihn mit https://github.com/Parteiduell/frontend/commit/9643c39d0cdbb8435cd70854aded1b8f96de1756. Ich weiß leider nicht mehr was das behoben hat. Ich meine aber, dass auch das einen andere Fehler behoben hat.

**Comment by gruselhaus** [comment]
Wir haben das damals echt kompliziert gebaut... ich versuche mich gerade reinzudenken...

**Comment by gruselhaus** [comment]
Ich hoffe 62c006a behebt den Fehler jetzt ein für alle mal.
