### ISSUE TITLE
Toggle Dark Mode

### ISSUE THREAD

**Issue by gruselhaus** [Parteiduell/frontend#55]
@jnnkB kannst Du irgendwie ne Möglichkeit schaffen, dass der Dark Mode nicht Default ist, sondern erst aktiviert werden muss?

**Comment by gruselhaus** [comment]
wow cool, danke 🎉

**Comment by jnnkB** [comment]
Wenn man mal Zeit hat kann vllt. statt dem Select so nen Bitten mit drei Feldern verwenden
